"""Counterexample-driven test synthesizer.

Property-based testing typically finds a counterexample and stops.
:func:`render_test` turns the counterexample into a permanent
regression test — runnable pytest source pinning the failure as a
CI gate. Failure → test → CI gate, in one function call.

    >>> import sympy as sp
    >>> from eml_rewrite import find_counterexample, render_test
    >>>
    >>> u = sp.Symbol("u")
    >>> cx = find_counterexample(sp.log(u**2), 2 * sp.log(u))
    >>> src = render_test(cx, name="test_log_pow_negative_branch")
    >>> print(src)              # doctest: +SKIP
    def test_log_pow_negative_branch():
        \"\"\"Generated by eml_rewrite.render_test from a Counterexample.\"\"\"
        import sympy as sp
        before = log(Pow(Symbol('u'), Integer(2)))
        after = Mul(Integer(2), log(Symbol('u')))
        ...
        assert val_before != val_after, \"...\"

The emitted source uses :func:`sympy.srepr` for expression
serialization (round-trips losslessly via ``eval`` with the
``sympy`` namespace) and binds the substitution point to the
expressions' actual free symbols by name, so assumption-bearing
symbols (positive, real, ...) substitute correctly.
"""
from __future__ import annotations

import sympy as sp

from .core import Counterexample


__all__ = ["render_test"]


def render_test(
    cx: Counterexample,
    *,
    name: str = "test_counterexample_regression",
    precision: int = 15,
) -> str:
    """Render a runnable pytest test that pins ``cx`` as a regression case.

    Parameters
    ----------
    cx:
        A :class:`Counterexample` returned by :func:`find_counterexample`.
        Must have ``before_expr`` and ``after_expr`` populated (they
        are by ``find_counterexample``; manual constructions need to
        pass them).
    name:
        The generated function's name. Defaults to
        ``"test_counterexample_regression"``. Pytest discovery picks
        up any ``test_*`` name.
    precision:
        Decimal digits for ``sp.N(..., precision)``. Default 15
        matches the float-precision boundary; raise for stricter
        comparison or where catastrophic cancellation lurks.

    Returns
    -------
    str
        Python source code for the regression test. Self-contained
        except for ``sympy`` (imported inside the function body).
    """
    if cx.before_expr is None or cx.after_expr is None:
        raise ValueError(
            "render_test requires Counterexample with before_expr and "
            "after_expr populated. (find_counterexample populates them; "
            "manual constructions must pass them explicitly.)"
        )

    # sp.srepr produces a string of unqualified SymPy class calls
    # (e.g., ``log(Pow(Symbol('u'), Integer(2)))``). ``sp.S(...)``
    # round-trips it under the sympy namespace, including symbol
    # assumptions, without us needing ``from sympy import *`` in the
    # generated test file.
    before_src = repr(sp.srepr(cx.before_expr))
    after_src = repr(sp.srepr(cx.after_expr))

    syms = list(cx.symbols)
    if syms:
        point_pairs = ", ".join(
            f"{s.name!r}: {p!r}" for s, p in zip(syms, cx.point)
        )
        point_block = (
            f"    point_by_name = {{{point_pairs}}}\n"
            f"    free_syms = {{s.name: s for s in (before.free_symbols | after.free_symbols)}}\n"
            f"    subs = {{free_syms[name]: value for name, value in point_by_name.items() if name in free_syms}}\n"
        )
        eval_block = (
            f"    val_before = sp.N(before.subs(subs), {precision})\n"
            f"    val_after = sp.N(after.subs(subs), {precision})\n"
        )
    else:
        # No free symbols — direct constant comparison.
        point_block = "    # no free symbols\n"
        eval_block = (
            f"    val_before = sp.N(before, {precision})\n"
            f"    val_after = sp.N(after, {precision})\n"
        )

    note_lines = [f"# kind: {cx.kind}"]
    if cx.note:
        note_lines.append(f"# note: {cx.note}")
    if cx.before_value is not None or cx.after_value is not None:
        note_lines.append(
            f"# recorded values: before={cx.before_value!r}, after={cx.after_value!r}"
        )
    note_block = "".join(f"    {ln}\n" for ln in note_lines)

    assertion = (
        '    assert val_before != val_after, (\n'
        '        f"counterexample regression: before={val_before} == after={val_after}"\n'
        '    )\n'
    )

    return (
        f"def {name}():\n"
        f'    """Generated by eml_rewrite.render_test from a Counterexample."""\n'
        f"    import sympy as sp\n"
        f"    before = sp.S({before_src})\n"
        f"    after = sp.S({after_src})\n"
        f"{note_block}"
        f"{point_block}"
        f"{eval_block}"
        f"{assertion}"
    )
